<?php

return [
    'attributes' => [
        'physical' => [
            ['key' => 'strength', 'display_name' => 'Strength', 'sort_order' => 1],
            ['key' => 'dexterity', 'display_name' => 'Dexterity', 'sort_order' => 2],
            ['key' => 'stamina', 'display_name' => 'Stamina', 'sort_order' => 3],
        ],
        'social' => [
            ['key' => 'charisma', 'display_name' => 'Charisma', 'sort_order' => 4],
            ['key' => 'manipulation', 'display_name' => 'Manipulation', 'sort_order' => 5],
            ['key' => 'appearance', 'display_name' => 'Appearance', 'sort_order' => 6],
        ],
        'mental' => [
            ['key' => 'perception', 'display_name' => 'Perception', 'sort_order' => 7],
            ['key' => 'intelligence', 'display_name' => 'Intelligence', 'sort_order' => 8],
            ['key' => 'wits', 'display_name' => 'Wits', 'sort_order' => 9],
        ],
    ],
    'abilities' => [
        'talents' => [
            ['key' => 'alertness', 'display_name' => 'Alertness', 'sort_order' => 10],
            ['key' => 'athletics', 'display_name' => 'Athletics', 'sort_order' => 11],
            ['key' => 'awareness', 'display_name' => 'Awareness', 'sort_order' => 12],
            ['key' => 'brawl', 'display_name' => 'Brawl', 'sort_order' => 13],
            ['key' => 'empathy', 'display_name' => 'Empathy', 'sort_order' => 14],
            ['key' => 'expression', 'display_name' => 'Expression', 'sort_order' => 15],
            ['key' => 'intimidation', 'display_name' => 'Intimidation', 'sort_order' => 16],
            ['key' => 'leadership', 'display_name' => 'Leadership', 'sort_order' => 17],
            ['key' => 'streetwise', 'display_name' => 'Streetwise', 'sort_order' => 18],
            ['key' => 'subterfuge', 'display_name' => 'Subterfuge', 'sort_order' => 19],
        ],
        'skills' => [
            ['key' => 'animal_ken', 'display_name' => 'Animal Ken', 'sort_order' => 20],
            ['key' => 'crafts', 'display_name' => 'Crafts', 'sort_order' => 21],
            ['key' => 'drive', 'display_name' => 'Drive', 'sort_order' => 22],
            ['key' => 'etiquette', 'display_name' => 'Etiquette', 'sort_order' => 23],
            ['key' => 'firearms', 'display_name' => 'Firearms', 'sort_order' => 24],
            ['key' => 'larceny', 'display_name' => 'Larceny', 'sort_order' => 25],
            ['key' => 'melee', 'display_name' => 'Melee', 'sort_order' => 26],
            ['key' => 'performance', 'display_name' => 'Performance', 'sort_order' => 27],
            ['key' => 'stealth', 'display_name' => 'Stealth', 'sort_order' => 28],
            ['key' => 'survival', 'display_name' => 'Survival', 'sort_order' => 29],
        ],
        'knowledges' => [
            ['key' => 'academics', 'display_name' => 'Academics', 'sort_order' => 30],
            ['key' => 'computer', 'display_name' => 'Computer', 'sort_order' => 31],
            ['key' => 'finance', 'display_name' => 'Finance', 'sort_order' => 32],
            ['key' => 'investigation', 'display_name' => 'Investigation', 'sort_order' => 33],
            ['key' => 'law', 'display_name' => 'Law', 'sort_order' => 34],
            ['key' => 'medicine', 'display_name' => 'Medicine', 'sort_order' => 35],
            ['key' => 'occult', 'display_name' => 'Occult', 'sort_order' => 36],
            ['key' => 'politics', 'display_name' => 'Politics', 'sort_order' => 37],
            ['key' => 'science', 'display_name' => 'Science', 'sort_order' => 38],
            ['key' => 'technology', 'display_name' => 'Technology', 'sort_order' => 39],
        ],
    ],
    'backgrounds' => [
        ['key' => 'allies', 'display_name' => 'Allies', 'sort_order' => 40],
        ['key' => 'contacts', 'display_name' => 'Contacts', 'sort_order' => 41],
        ['key' => 'domain', 'display_name' => 'Domain', 'sort_order' => 42],
        ['key' => 'fame', 'display_name' => 'Fame', 'sort_order' => 43],
        ['key' => 'generation', 'display_name' => 'Generation', 'sort_order' => 44],
        ['key' => 'herd', 'display_name' => 'Herd', 'sort_order' => 45],
        ['key' => 'influence', 'display_name' => 'Influence', 'sort_order' => 46],
        ['key' => 'mentor', 'display_name' => 'Mentor', 'sort_order' => 47],
        ['key' => 'resources', 'display_name' => 'Resources', 'sort_order' => 48],
        ['key' => 'retainers', 'display_name' => 'Retainers', 'sort_order' => 49],
        ['key' => 'status', 'display_name' => 'Status', 'sort_order' => 50],
    ],
    'virtues' => [
        ['key' => 'conscience', 'display_name' => 'Conscience/Conviction', 'sort_order' => 51],
        ['key' => 'self_control', 'display_name' => 'Self-Control/Instinct', 'sort_order' => 52],
        ['key' => 'courage', 'display_name' => 'Courage', 'sort_order' => 53],
    ],
    'other' => [
        ['key' => 'humanity', 'display_name' => 'Humanity/Path', 'sort_order' => 54, 'maximum' => 10],
        ['key' => 'willpower', 'display_name' => 'Willpower', 'sort_order' => 55, 'maximum' => 10],
    ],
    'health_boxes' => [
        ['index' => 0, 'label' => 'Bruised', 'penalty' => 0],
        ['index' => 1, 'label' => 'Hurt', 'penalty' => -1],
        ['index' => 2, 'label' => 'Injured', 'penalty' => -1],
        ['index' => 3, 'label' => 'Wounded', 'penalty' => -2],
        ['index' => 4, 'label' => 'Mauled', 'penalty' => -2],
        ['index' => 5, 'label' => 'Crippled', 'penalty' => -5],
        ['index' => 6, 'label' => 'Incapacitated', 'penalty' => 0],
    ],
];
